Repository kheeyaa/lucky-ducky, pull requests merged in 2023-01, with the labels that each got.

#11 동전 던지기 추가
  .eslintrc.cjs
  .prettierrc
  package-lock.json
  package.json
  src/components/coin/Coin.svelte
  src/components/common/button.svelte
  src/routes/coin/+page.svelte
  src/utils/random.ts
  static/imgs/coins/heads-coin.png
  static/imgs/coins/tails-coin.png
Labels: enhancement, configuration

#15 feat: 인트로 페이지
  src/Layout/MobileLayout.svelte
  src/components/common/a11y/A11yhidden.svelte
  src/routes/+page.svelte
  static/imgs/intro/ducky.png
  static/imgs/intro/logo.png
Labels: enhancement

#16 feat: 글로벌 reset 스타일, font 추가
  static/style.scss
Labels: enhancement

#17 feat: start 버튼 스타일
  src/routes/+page.svelte
Labels: enhancement, style

#22 fix: 경주 스크롤 버그 수정
  src/components/race/Race.svelte
Labels: bug

#23 feat: 메인 페이지 개발
  src/Layout/MobileLayout.svelte
  src/components/main/ItemCard.svelte
  src/routes/+page.svelte
  src/routes/main/+page.svelte
  static/imgs/thumbnails/thumbnail_coin.svg
  static/imgs/thumbnails/thumbnail_ladder.svg
  static/imgs/thumbnails/thumbnail_lotto.svg
  static/imgs/thumbnails/thumbnail_race.svg
  static/imgs/thumbnails/thumbnail_raffle.svg
  static/imgs/thumbnails/thumbnail_spin.svg
Labels: enhancement

#26 chore: 포춘쿠키 운세 문구 데이터 추가
  src/data/fortune.json
Labels: data

#30 feat: 로또 번호 추출 기능 구현
  src/components/lotto/Lotto.svelte
  src/routes/lotto/+page.svelte
  src/utils/random.ts
Labels: enhancement
